### PR TITLE
Multipath in Chromium

### PR DESCRIPTION
**Pull request by ianswett**

### CODE REVIEW

**Comment by larseggert** [comment]
Do I merge this one, or https://github.com/quicwg/wg-materials/pull/165?

**Comment by ianswett** [comment]
This one, but let me do an update based on Lucas comments first.

**Comment by larseggert** [comment]
ACK

**Comment by ianswett** [comment]
I just updated the slides, so this is ready to submit.

**Comment by LPardue** [comment]
Thanks, merged.

**Pull request merged**
