### PR TITLE
Apple Multipath Use-Cases

### PR DESCRIPTION
**Pull request by cpaasch**
A short slide-deck describing Apple's use-cases and requirements for multipath and what is needed from QUIC.

### CODE REVIEW

**Comment by LPardue** [comment]
Thanks. These are clear and concise. @larseggert may have other comments. The only one I have is about path quality measurement - is the requirement for either endpoints to do be able to do this? And where exactly is the gap; is e.g. QUICv1 PING enough if you were able to have multiple paths or do you require something extra?

**Comment by cpaasch** [comment]
The goal of the path-quality measurement is to allow a host to measure the RTT of a path. Indeed, QUICv1-ping might be good enough for that.

I realize Slide 4 might not be clear enough here because MPTCP on Siri ends up transmitting on both paths simultaneously when Wi-Fi is low-RTT but high loss, while cell is high-RTT with little loss. "switching between paths" happens here at sub-RTT timeframes. I will update the slides after giving Lars a chance to provide feedback.

**Comment by LPardue** [comment]
Thanks Christoph.

**Comment by rpaulo** [comment]
@LPardue QUICv1 PING isn't enough because that forces the endpoint to switch to a new path. (Ab)using PATH_CHALLENGE is the way to get an RTT estimate in "interactive" mode.  This is somewhat explained in https://tools.ietf.org/html/draft-paulo-quic-migration-00

**Pull request merged**
