### PR TITLE
First draft of the slides on requirements from hybrid access networks

### PR DESCRIPTION
**Pull request by obonaventure**
Please find attached a first draft of the slides describing the requirements from the hybrid access networks use case for MPQUIC.

Let me know if you think that providing more information about MPTCP would be useful. I have plenty of slides on MPTCP and could easily explain some elements that would be useful for the QUIC community if needed

### CODE REVIEW

**Comment by LPardue** [comment]
Thanks. I've not spoke to @larseggert about this but it is not clear what an architecture for a multipath quic solution looks like. I think the WG need to understand how bandwidth aggregation would work in your proposal. Does it work end-to-end, or does it require some proxying or tunneling?

**Comment by obonaventure** [comment]
The currently deployed solution relies on proxies that are installed on the Hybrid CPEs and on a HAG running in the operator's network. I intended to explain this part using the slide with the architecture and the MPTCP connections. I can provide more details and more slides if needed. Multipath QUIC could be used with exactly the same architecture and replace MPTCP. This would provide several benefits, including the support of non-TCP traffic.

**Comment by larseggert** [comment]
So is the intent that MPQUIC would be a tunnel protocol, and not something where either of the endpoints are involved?

**Comment by obonaventure** [comment]
To mimic today's deployment, MPQUIC would start as a tunnel protocol. However, the current deployments use proxies because the end-to-end protocols like TCP, but also single path QUIC, do not allow to aggregate low bandwidth links. With MPQUIC, host could aggregate bandwidth by themselves using an end-to-end approach that is not possible today. As MPQUIC gets deployed, the two solutions (proxies for legacy protocols and end-to-end with MPQUIC) would probably coexist

**Comment by LPardue** [comment]
I don't think more slides are going to help, there are already 9 slides for a 5 minute slot. I think it would help to focus on what a multipath QUIC deployment would look like in your proxied and unproxied cases, and possibly describe how a client selects between these modes.

**Comment by obonaventure** [comment]
I can add a slide describing one possible deployment with end-to-end MPQUIC and summarise others. My understanding from Lars's email was that the WG members also needed some additional information on MPTCP was deployed and this is a very different deployment from Apple's one. I'll update the pull request later this evening.

**Comment by larseggert** [comment]
It might be useful to have two parts to this, one being a quick "here is what MPTCP offers" recap, and the second being the "here is our use case and what we're missing from QUICv1"

**Pull request merged**
