### PR TITLE
Create Multipath Steering Modes in 3GPP ATSSS.pdf

### PR DESCRIPTION
**Pull request by SpencerDawkins**

### CODE REVIEW

**Comment by larseggert** [comment]
Quick feedback, not discussed with @LPardue:

* Since this apparently uses QUIC as a tunnel between the endpoint and the UPF box, you should explain what the relationship with MASQUE is (if any) and motivate why this use of QUIC (vs. the usual deployment where the QUIC connection ends all the way at the far server) is in scope for us. It seems like any tunnel might do?

* For each of the steering modes, esp. the Rel 16 ones, it would be good to understand which can be supported by QUICv1 (and to what degree).
 
* Related to the previous point, for those steering modes that cannot be supported, it would be good to identify the missing functionality that would support them. It would also be good to understand who makes these steering decisions.

* I think we can cut slide 6.

**Comment by LPardue** [comment]
I agree with Lar's comments, especially wrt proxying/MASQUE. We need to be clear about end-to-end protocols because of the layering. I suspect proxied QUIC connections will want to avoid end-to-end migration or multipath. Also, maybe something for discussion, but the role of congestion comes into play. If tunneling QUIC-in-QUIC using DATAGRAM congestion might be manageable but if adopting something like https://github.com/ietf-wg-masque/wg-materials/blob/master/ietf108/slides-108-masque-optimizing-proxies-for-quic-00.pdf there could be a problem.

**Comment by SpencerDawkins** [comment]
First, the good news - I appreciate Lars' suggestion to say what's possible in QUICv1 with no changes (I added that in blue on the slides about steering modes). I also cut slide 6, although I hope the meeting discusses those topics (just not as part of my five minutes, which is fine). 

The overarching consideration, as I understand it, is that QUICv1 doesn't use more than one active path at a time. I marked three of the four steering modes on slide 4 as "could work in QUICv1 using migration", with the idea being that if your application has multiple paths and validate them, you could pick a validated path based on whatever and migrate to it", but the remaining five steering modes on slides 4 and 5 all use more than one path simultaneously.

Re: relationship with MASQUE - there are 14 potential solutions for various parts of ATSSS Phase 2 under study in SA2, and only one of them mentions MASQUE, and SA2 is meeting this week and next week, so I think it's getting ahead of 3GPP for me to try to characterize the relationship. 

Re: proxying - SA2 has potential solutions that use tunneling, and potential solutions that use proxying. Again, I think I'd be getting ahead of 3GPP to try to characterize what they are thinking. As mentioned, SA2 is meeting this week and next week and will almost certainly be clearer on what those paths look like after next Friday. 

I hope this helps - please let me know if you have questions (either here or in e-mail).

**Comment by larseggert** [comment]
The new slides are clearer, thanks! Two more questions:

1. When you say "network provides ATSSS rules" on slide 3, is it implied that the UE **must** then apply these rules, or does the UE have a say?

2.  Is the QUIC/multipath QUIC stack on the UE a tunnel endpoint, or is it intended to be the QUIC stack that ships with an app on the UE?

**Comment by SpencerDawkins** [comment]
Hi, Lars, 

I think it's correct to say that Phase 1/Release 16 UEs are expected to apply the rules (as well as the UPF). I don't know how much checking "the network" is supposed to do, to make sure that the UEs behave, but since the network is doing measurements, it's not clear you'd gain much by ignoring the rules. 

That's one of the things that's under active discussion in Phase 2/Release 17 - the autonomous, autonomous with advanced PMF, and UE-assisted modes, at a minimum, are all about the UEs deciding to do things without being told to do them. 

The question about the QUIC/multipath QUIC stack might not have an answer yet. SA2 is still working at Stage 2, so I haven't seen that discussed.

**Comment by larseggert** [comment]
The answer to (2) matters *a lot*. Because if 3GPP is working on a design that assumes that end-application stacks will be influenced by what the network tells them, they are IMO designing for an unlikely future.

**Comment by SpencerDawkins** [comment]
Hi, Lars,

That would certainly make a tunnel endpoint that ships with the UE more likely. 

I'm mostly saying that I can't point to discussions in 3GPP that would answer your question, not that the question and answer aren't important!

**Comment by SpencerDawkins** [comment]
I've updated my slides based on feedback from Mirja. If I need to update anything based on presentation merging or non-merging, I'm happy to do that!

**Pull request merged**
