### PR TITLE
MPQUIC use cases from Alibaba

### PR DESCRIPTION
**Pull request by QingAn**
MPQUIC use cases from Alibaba

### CODE REVIEW

**Comment by LPardue** [comment]
Thanks. Can you clarify what multipath QUIC technology you are discussing on the slides? Is it https://tools.ietf.org/html/draft-deconinck-quic-multipath-05 or something else?

It would help to see clear requirements of the QUIC transport. What do you need in addition to QUICv1 for your use case to function?

The slides imply that the deployment requires client and server support for multipath QUIC. Is that correct?

Can you say anything about the application protocols that you have been using? Is it HTTP/3 or something else

**Comment by Yanmei-Liu** [comment]
Hi, Lucas

Q1: Can you clarify what multipath QUIC technology you are discussing on the slides?
The multipath QUIC technology we are discussing on the slides: [https://tools.ietf.org/html/draft-an-multipath-quic-application-policy-00](https://tools.ietf.org/html/draft-an-multipath-quic-application-policy-00). We will update a new version with more protocol details recently.

Q2: What do you need in addition to QUICv1 for your use case to function?
We use QUICv1 in the Taobao mobile application. QUICv1 has connection migration in QUIC transport, it's useful when mobile phone switch from Wi-Fi to cellular(or the reverse), but we want to use both Wi-Fi and Cellular network at the same time. That's the reason why we need Multipath QUIC.

Q3: The slides imply that the deployment requires client and server support for multipath QUIC. Is that correct?
Yes.

Q4: Can you say anything about the application protocols that you have been using? Is it HTTP/3 or something else?
We are using HTTP/3 in short-form video downloading, and an upload application protocol in video/file uploading with QUIC transport.

**Comment by LPardue** [comment]
Thanks for the answers.

> The multipath QUIC technology we are discussing on the slides: https://tools.ietf.org/html/draft-an-multipath-quic-application-policy-00. We will update a new version with more protocol details recently.

So if I understand correctly, you are running additional policies on top of https://tools.ietf.org/html/draft-deconinck-quic-multipath-05. If so, please state clearly on the slides. It would also be interesting to state in clear and concise terms what you needed to add.

> We use QUICv1 in the Taobao mobile application. QUICv1 has connection migration in QUIC transport, it's useful when mobile phone switch from Wi-Fi to cellular(or the reverse), but we want to use both Wi-Fi and Cellular network at the same time. That's the reason why we need Multipath QUIC.

I see you have requirements on each of the use case. It would help to summarise all of the requirements on a single slide at the end.

> We are using HTTP/3 in short-form video downloading, and an upload application protocol in video/file uploading with QUIC transport.

That's an interesting detail. Can you add it to the slides please? (we don't need all the details of your video upload protocol, just if it needs streams, datagrams, both etc.).

As a more general comment. I don't think we'll have time to show the demonstration video during your slot, the logistics of playing video to WebEx don't help here.

**Comment by yfmascgy** [comment]
Q1: So if I understand correctly, you are running additional policies on top of https://tools.ietf.org/html/draft-deconinck-quic-multipath-05. If so, please state clearly on the slides. It would also be interesting to state in clear and concise terms what you needed to add.

>  There have been some major differences between our implementation and the draft you mentioned above. According to our experience, we found those differences necessary due to practical considerations. We will add additional information and clarify this point in the presentation. 

Q2: I see you have requirements on each of the use case. It would help to summarise all of the requirements on a single slide at the end.

>  Sure. That's really a good suggestion, so we will put one more summary slide at the end.

Q3 That's an interesting detail. Can you add it to the slides please? (we don't need all the details of your video upload protocol, just if it needs streams, datagrams, both etc.).

> No problem. We can put some of those details.

Q4 As a more general comment. I don't think we'll have time to show the demonstration video during your slot, the logistics of playing video to WebEx don't help here.

> Understood. If so, maybe we can put a link to the demo in the slide so anyone interested can refer to it later on.

**Comment by yfmascgy** [comment]
Hi Lucas,

One more question regarding the demo. As it is only 15 seconds long, do you think it would be possible to fit into the presentation slot? Please advise:)

**Comment by larseggert** [comment]
If you end up with time left, we can do that.

**Pull request merged**
